# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordinateGenerator
                                 A QGIS plugin
 This plugin generates coordinate files from selected polygons.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-18
        copyright            : (C) 2024 by Hiago Cardoso Arquitetura e Urbanismo
        email                : hiagocardoso.arq@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# Avoid warnings about compliance with the PEP 8 style guide (standard Python naming convention)
# (which suggests class names start with capitalized letters)
# 
# Pylint is a tool that checks Python code for potential errors
# Pylint is being told that a specific naming convention is being followed
# Due to compatibility with the QGIS plugin system

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordinateGenerator class from file CoordinateGenerator.

    :param iface: A QGIS interface instance
    :type iface: QgsInterface
    """

    # imports the CoordinateGenerator class from coordinate_generator.py file
    # (which resides in the same directory, indicated by the dot .)
    from .coordinate_generator import CoordinateGenerator

    # returns a new instance of the CoordinateGenerator class
    # passes the iface instance (QGIS interface instance) to the class constructor
    return CoordinateGenerator(iface)
