# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordinateGeneratorDialog
                                 A QGIS plugin
 This plugin generates coordinate files from selected polygons.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-18
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Hiago Cardoso Arquitetura e Urbanismo
        email                : hiagocardoso.arq@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsProject

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'coordinate_generator_dialog_base.ui'))

class CoordinateGeneratorDialog(QtWidgets.QDialog, FORM_CLASS):
    """QGIS Plugin Dialog."""

    def __init__(self, iface, parent=None):
        """Constructor.
        
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        # The super() function is used to call methods of the superclass (or parent class)
        # Clls the constructor of the superclass QDialog
        # parent refers to the parent window of the graphical user interface
        # Ensures that the dialog is displayed correctly in the context of the QGIS interface.
        super(CoordinateGeneratorDialog, self).__init__(parent)

        # Set up the user interface from Designer through FORM_CLASS
        self.setupUi(self)
        
        # Check if QGIS interface (iface) is available
        if iface is None:

            # Display error message if interface is not available
            QMessageBox.critical(None, "Error", "QGIS interface is not available.")

            # Encerra o método construtor
            return

        # Stores the iface reference
        self.iface = iface

        # Connect the select folder button to the corresponding method
        self.btnSelectFolder.clicked.connect(self.open_folder_dialog)

    def open_folder_dialog(self):
        """Opens a dialog to select an existing operating system folder."""

        # Open the dialog to select a folder
        folder = QFileDialog.getExistingDirectory(self, "Select Folder")

        # Checks if a folder is selected
        if folder:

            # Set the folder path in the QTextBrowser
            self.txtSelectFolder.setPlainText(folder)
